def generate_public_key(generator: int, private_key: int, prime: int) -> str:
    """Returns a public key generated by using a private key."""
    return str(pow(generator, private_key, prime))


def generate_encryption_key(private_key: int, public_key: int, prime: int) -> str:
    """Returns a key created with a private and public key."""
    return str(pow(public_key, private_key, prime))
